[ftplugin]
denite = '''
nnoremap <silent><buffer><expr> <cr>    denite#do_map('do_action')
nnoremap <silent><buffer><expr> <tab>   denite#do_map('choose_action')
nnoremap <silent><buffer><expr> <c-l>   denite#do_map('redraw')
nnoremap <silent><buffer><expr> <esc>   denite#do_map('quit')
nnoremap <silent><buffer><expr> <space> denite#do_map('toggle_select').'j'
nnoremap <silent><buffer><expr> *       denite#do_map('toggle_select_all')
nnoremap <silent><buffer><expr> i       denite#do_map('open_filter_buffer')
nnoremap <silent><buffer><expr> u       denite#do_map('restore_sources')
nnoremap <silent><buffer><expr> -       denite#do_map('move_up_path')
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
let g:EasyMotion_verbose = 0
'''

[[plugins]]
repo = 'haya14busa/is.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
let g:edge_enable_italic = 1
colorscheme edge
'''

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
hook_add = "lua require'plugin_settings.nvim-colorizer'"

[[plugins]]
repo = 'hardcoreplayers/spaceline.vim'
hook_add = "lua require'plugin_settings.spaceline'"

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_source = "lua require'plugin_settings.denite'"

[[plugins]]
repo = 'tk-shirasaka/denite-utils'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = "lua require'plugin_settings.deoplete'"

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_source = "lua require'plugin_settings.nvim-lspconfig'"

[[plugins]]
repo = 'nvim-lua/diagnostic-nvim'

[[plugins]]
repo = 'Shougo/deoplete-lsp'
hook_source = '''
call deoplete#lsp#enable()
'''

[[plugins]]
repo = 'zchee/deoplete-zsh'

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = 'let g:deol#prompt_pattern = "% \|%$"'

[[plugins]]
repo = 'tk-shirasaka/ejdict.nvim'

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
let g:vista_default_executive = 'nvim_lsp'
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_source = "lua require'plugin_settings.nvim-treesitter'"

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-refactor'
hook_source = "lua require'plugin_settings.nvim-treesitter-refactor'"

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'
hook_source = "lua require'plugin_settings.nvim-treesitter-textobjects'"

[[plugins]]
repo = 'nvim-treesitter/playground'
hook_source = "lua require'plugin_settings.nvim-treesitter-playground'"

[[plugins]]
repo = 'mfussenegger/nvim-dap'
hook_source = "lua require'plugin_settings.dap'"

[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'
hook_add = "lua require'plugin_settings.vim-dadbod-ui'"

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-completion'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
