[ftplugin]
denite = '''
nnoremap <silent><buffer><expr> <cr> denite#do_map('do_action')
nnoremap <silent><buffer><expr> <tab> denite#do_map('choose_action')
nnoremap <silent><buffer><expr> <c-l> denite#do_map('redraw')
nnoremap <silent><buffer><expr> <space> denite#do_map('toggle_select').'j'
nnoremap <silent><buffer><expr> * denite#do_map('toggle_select_all')
nnoremap <silent><buffer><expr> i denite#do_map('open_filter_buffer')
nnoremap <silent><buffer><expr> q denite#do_map('quit')
'''
denite-filter = '''
inoremap <silent><buffer><expr> <cr> denite#do_map('do_action')
inoremap <silent><buffer><expr> <tab> denite#do_map('choose_action')
inoremap <silent><buffer><expr> <c-l> denite#do_map('redraw')
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'haya14busa/is.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'sheerun/vim-polyglot'
build = 'bash ./build'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'colorscheme onedark'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_theme = 'onedark'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_buffers = 0
let g:airline_powerline_fonts = 1
'''

[[plugins]]
repo = 'joonty/vdebug'
hook_add = '''
let g:vdebug_keymap = {
    \ 'run': '<space>vr',
    \ 'run_to_cursor': '<space>vc',
    \ 'step_over': '<space>vj',
    \ 'step_into': '<space>vl',
    \ 'step_out': '<space>vh',
    \ 'close': '<space>vq',
    \ 'detach': '<space>vd',
    \ 'set_breakpoint': '<space>vb',
    \ 'get_context': '<space>v*',
    \ 'eval_under_cursor': '<space>v?',
    \ 'eval_visual': '<space>v?',
\ }
let g:vdebug_options = {'break_on_open': 0, 'port': 9000, 'server': '0.0.0.0', 'path_maps': {'/var/www/html/': '/path/to/repos/'}}
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_source = '''
call denite#custom#var('file/rec', 'command', ['rg', '--files', '--glob', '!.git'])
call denite#custom#var('grep', 'command', ['rg'])
call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep', '--no-heading'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
call denite#custom#option('_', {'auto_resume': 1, 'start_filter': 1, 'split': 'floating'})
call denite#custom#source('grep', 'converters', ['converter/abbr_word'])
call denite#custom#source('file,file/rec,file/old,buffer,git/status,git/file', 'converters', ['devicons_denite_converter'])
'''

[[plugins]]
repo = 'tk-shirasaka/denite-utils'
hook_add = 'noremap <silent><tab> :Denite -buffer-name=main command:Denite command command::history<CR>'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
call deoplete#enable()
call deoplete#custom#option({'ignore_case': 1})
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = 'bash install.sh'
rev = 'next'
hook_add = '''
let g:LanguageClient_serverCommands = {
    \ 'python': ['pyls'],
    \ 'go': ['bingo'],
    \ 'php': ['php', '/root/.composer/vendor/bin/php-language-server.php'],
    \ 'javascript.jsx': ['javascript-typescript-stdio'],
    \ 'typescript': ['typescript-language-server', '--stdio'],
\ }
'''

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
